#!/usr/bin/env bash
set -euE

acc new "$1" --template haskell
# mkdir "$1"

cp haskell/package.yaml "$1"
cp haskell/stack.yaml "$1"
cat haskell/hie.yaml | sed "s;_acc;$1;g" > "$1/hie.yaml"
cat haskell/_acc.cabal | sed "s;_acc;$1;g" > "$1/$1.cabal"

: > "$1/.projectile"
