dependencies:
  - base >= 4.7 && < 5
  - bytestring

# DRY for package.yaml executables:
# <https://www.reddit.com/r/haskell/comments/haeqin/dry_for_packageyaml_executables/>
_exe-defs: &exe-defaults
  # dependencies:
  # - abs
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall # all warnings
  other-modules: []

# REMARK: See `README` for the langauge server support.
executables:
  001-exe:
    <<: *exe-defaults
    source-dirs: "001"
    main:                Main.hs

  002-exe:
    <<: *exe-defaults
    source-dirs: "002"
    main:                Main.hs

  003-exe:
    <<: *exe-defaults
    source-dirs: "003"
    main:                Main.hs

  004-exe:
    <<: *exe-defaults
    source-dirs: "004"
    main:                Main.hs

  005-exe:
    <<: *exe-defaults
    source-dirs: "005"
    main:                Main.hs

  006-exe:
    <<: *exe-defaults
    source-dirs: "006"
    main:                Main.hs

  007-exe:
    <<: *exe-defaults
    source-dirs: "007"
    main:                Main.hs

  008-exe:
    <<: *exe-defaults
    source-dirs: "008"
    main:                Main.hs

  009-exe:
    <<: *exe-defaults
    source-dirs: "009"
    main:                Main.hs

  055-exe:
    <<: *exe-defaults
    source-dirs: "055"
    main:                Main.hs
