dependencies:
  - base >= 4.7 && < 5
  - bytestring

# DRY for package.yaml executables:
# <https://www.reddit.com/r/haskell/comments/haeqin/dry_for_packageyaml_executables/>
_exe-defs: &exe-defaults
  # dependencies:
  # - abs
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall # all warnings
  other-modules: []

# REMARK: See `README` for the langauge server support.
executables:
  q359-exe:
    <<: *exe-defaults
    source-dirs: "greedy/q359"
    main:                Main.hs
